# -*- coding: utf-8 -*-
"""Multi-Agent AI Decision Support System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uW2zsDKLR1Xgr-u9JiG_UFGXsaiBePi9

# Drive Mounting & Dependencies Installation
"""

from google.colab import drive
drive.mount('/content/drive')

!cd /content/drive/MyDrive/Books_for_agents

!pip install groq langchain langchain-community sentence-transformers faiss-cpu pypdf langchain-text-splitters

"""# Multi-Agent System - Supervisor Approach"""

import os
import time
from google.colab import drive
from groq import Groq
from langchain_community.document_loaders import PyPDFLoader
from langchain_community.vectorstores import FAISS
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_text_splitters import RecursiveCharacterTextSplitter # Updated import
from google.colab import userdata
# 1. Mount Google Drive
drive.mount('/content/drive')
BASE_PATH = "/content/drive/MyDrive/Books_for_agents"

# Initialize Groq Client
# Ensure your API key is set in Colab's secrets or environment variables
client = Groq(api_key=userdata.get("GROQ_API_KEY"))

# 2. Define Agent Configurations
agents = [
    {
        "name": "Johann_Hari",
        "role": "The Compassionate Scientist",
        "book": "Lost Connections",
        "file_name": "Lost_Connections.pdf",
        "model": "llama-3.3-70b-versatile",
        "system_prompt": (
            "You are the Compassionate Scientist. Base your reasoning on neuroscience, psychology, "
            "and real human experiences. You are validating and empathetic, but your advice is rooted "
            "in research. Speak respectfully, validate the person's anxiety, and look for systemic or "
            "psychological root causes."
        )
    },
    {
        "name": "Kerry_Patterson",
        "role": "The Strategic Coach",
        "book": "Crucial Conversations",
        "file_name": "Crucial_Conversations.pdf",
        "model": "llama-3.3-70b-versatile",
        "system_prompt": (
            "You are the Strategic Coach. Your reasoning is direct, practical, and action-oriented. "
            "You are structured and disciplined. Give a clear playbook and expect execution. "
            "Professional but not cold; you want them to succeed. Speak like a consultant: "
            "'Here's the framework, here's the technique, now go apply it.' No fluff, all results."
        )
    },
    {
        "name": "Heath_Brothers",
        "role": "The Practical Problem-Solver",
        "book": "Decisive",
        "file_name": "Decisive.pdf",
        "model": "llama-3.3-70b-versatile",
        "system_prompt": (
            "You are the Practical Problem-Solver. You are friendly, clear-headed, and grounded. "
            "Focus on avoiding decision traps, considering "
            "multiple perspectives, and building confidence."
            "Be to the point and concise."
        )
    }
]

# 3. RAG Setup Function
def setup_rag_for_agent(agent_config):
    file_path = os.path.join(BASE_PATH, agent_config["file_name"])
    if not os.path.exists(file_path):
        print(f"Warning: PDF not found at {file_path}. Agent will run without RAG context.")
        return None

    print(f"Loading and indexing {agent_config['file_name']}...")
    loader = PyPDFLoader(file_path)
    docs = loader.load()

    text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
    splits = text_splitter.split_documents(docs)

    # Using HuggingFace embeddings as they are free and run locally in Colab
    embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")
    vectorstore = FAISS.from_documents(splits, embeddings)
    return vectorstore

# Build vector stores for all agents
vector_stores = {agent["name"]: setup_rag_for_agent(agent) for agent in agents}

# 4. Core Functions
def get_rag_context(vectorstore, query):
    if not vectorstore:
        return ""
    docs = vectorstore.similarity_search(query, k=3)
    return "\n".join([doc.page_content for doc in docs])

def generate_agent_response(agent, scenario, vectorstore):
    """Generate a single, focused response from an agent based on their perspective and book."""
    # Retrieve relevant book context based on the scenario
    context = get_rag_context(vectorstore, scenario)

    prompt = (
        f"Scenario:\n{scenario}\n\n"
        f"Relevant excerpts from '{agent['book']}':\n{context}\n\n"
        "Provide your analysis and recommendations based on your perspective and the book's principles. "
        "Keep your response concise and practical (under 200 words)."
    )

    try:
        completion = client.chat.completions.create(
            model=agent["model"],
            messages=[
                {"role": "system", "content": agent["system_prompt"]},
                {"role": "user", "content": prompt}
            ],
            temperature=0.7,
            max_tokens=350
        )
        return completion.choices[0].message.content
    except Exception as e:
        return f"[Error generating response: {e}]"

def supervisor_synthesis(scenario, agent_responses):
    """
    Supervisor analyzes all 3 agent responses and provides a final,
    concise, organized, and structured answer.
    """
    responses_text = "\n".join([
        f"\n--- {resp['agent']} ({resp['role']}) ---\n{resp['content']}"
        for resp in agent_responses
    ])

    prompt = (
        f"Scenario:\n{scenario}\n\n"
        f"Analysis from Three Perspectives:\n{responses_text}\n\n"
        "You are the Supervisor. Synthesize these three perspectives into a final, "
        "concise, and well-structured action plan. The output should be:\n"
        # "1. **Key Insights** - Main points across all perspectives (2-3 bullet points)\n" # remove
        "**Recommended Action Plan** - Clear, actionable steps (3-5 steps)\n"
        # "3. **Success Factors** - What to focus on for best results (2-3 points)\n\n" # remove
        "Be concise and practical. Aim for less than 200 words total." # 300-400 words total." # 200
    )

    completion = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content":
                "You are a supervisor who synthesizes diverse expert perspectives into clear, "
                "actionable guidance. You are organized, decisive, and strategic."},
            {"role": "user", "content": prompt}
        ],
        temperature=0.7,
        max_tokens=600
    )

    return completion.choices[0].message.content

# 5. Main Execution Loop - Supervisor Pattern
if __name__ == "__main__":
    # scenario = (
    #     "A student does not finish assigned work before deadline set by his supervisor. "
    #     "He notifies the supervisor late through email, 1 hour before the scheduled meeting. "
    #     "He doesn't get a reply. "
    #     "Meeting time passes and still no response from the supervisor.\n"
    #     "Problem: "
    #     "The student feels irresponsible and not sure about the suitable approach to the professor: "
    #     "shall he be apologetic or act as if nothing happened"
    # )

    # scenario = (
    #     "A software developer is working on a heavy project that consumes his mind all day. "
    #     "Even after work, his mind is trying to solve challenges faced through that day. "
    #     "This situation stays long enough for him to have a burnout. "
    #     "He tries to convey the message to the team leader, but faces a push to just keep working more. \n"
    #     "Problem: "
    #     "The software developer feels burnt out, unable to focus any more, and does not receive emotional support from his team leader. "
    #     "He is unsure about the best decision to save both his mental health and career."
    # )

    scenario = (
        "An accountant got laid off late in his career at the age of 55. "
        "Angry by the decision of the corporate where he spent nearly half his life, feels he shouldn't trust any employer anymore. "
        "He has a lot of family expenses to care for and needs an income. "
        "He's still not comfortable about working for someone again, so he starts thinking about starting his own business in accounting.\n"
        "Problem: "
        "The accountant understands the risk in starting a business and that it may take a long time to start generating an income large enough to cover his expenses. "
        "He's not able to weigh the risk against the possible benefits to take a decision."
    )

    print("=" * 70)
    print("SUPERVISOR PATTERN - MULTI-AGENT DECISION SUPPORT SYSTEM")
    print("=" * 70)
    print(f"\nScenario:\n{scenario}\n")
    print("=" * 70)

    # Step 1: Collect responses from all 3 agents
    print("\n[PHASE 1: COLLECTING AGENT PERSPECTIVES]\n")
    agent_responses = []

    for agent in agents:
        print(f"[{agent['name']} is analyzing...]")
        response = generate_agent_response(
            agent=agent,
            scenario=scenario,
            vectorstore=vector_stores[agent["name"]]
        )

        agent_responses.append({
            "agent": agent["name"],
            "role": agent["role"],
            "content": response
        })

        print(f"\n{agent['name']} ({agent['role']}):\n{response}\n")
        print("-" * 70)

        # Rate limit protection for Groq
        time.sleep(2)

    # Step 2: Supervisor synthesizes the responses
    print("\n[PHASE 2: SUPERVISOR SYNTHESIS]\n")
    print("[Supervisor is analyzing all perspectives and creating final recommendation...]\n")
    time.sleep(2)

    final_answer = supervisor_synthesis(scenario, agent_responses)

    print("=" * 70)
    print("SUPERVISOR'S FINAL RECOMMENDATION")
    print("=" * 70)
    print(f"\n{final_answer}\n")
    print("=" * 70)

"""# Single Agent System"""

import os
import time
from google.colab import drive
from groq import Groq
from langchain_community.document_loaders import PyPDFLoader
from langchain_community.vectorstores import FAISS
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_text_splitters import RecursiveCharacterTextSplitter
from google.colab import userdata

# Mount Google Drive

drive.mount('/content/drive')
BASE_PATH = "/content/drive/MyDrive/Books_for_agents"

# Initialize Groq Client
client = Groq(api_key=userdata.get("GROQ_API_KEY"))

# Books
books = [
    {
        "name": "Lost Connections",
        "file_name": "Lost_Connections.pdf"
    },
    {
        "name": "Crucial Conversations",
        "file_name": "Crucial_Conversations.pdf"
    },
    {
        "name": "Decisive",
        "file_name": "Decisive.pdf"
    }
]

# RAG Database
def setup_rag_for_book(book):
    file_path = os.path.join(BASE_PATH, book["file_name"])

    if not os.path.exists(file_path):
        print(f"Warning: {book['file_name']} not found. Skipping.")
        return None

    print(f"Loading and indexing {book['file_name']}...")

    loader = PyPDFLoader(file_path)
    docs = loader.load()

    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=500,
        chunk_overlap=300
    )
    splits = text_splitter.split_documents(docs)

    embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")
    vectorstore = FAISS.from_documents(splits, embeddings)

    return vectorstore

# Build vector stores
vector_stores = {
    book["name"]: setup_rag_for_book(book)
    for book in books
}


# RAG Retrieval

def get_rag_context(vectorstore, query, k=2):
    if not vectorstore:
        return ""
    docs = vectorstore.similarity_search(query, k=k)
    return "\n".join([doc.page_content for doc in docs])

# Single-Agent Decision Function
def single_agent_decision(scenario, vector_stores):
    contexts = []

    # Retrieve from all books
    for book_name, vs in vector_stores.items():
        context = get_rag_context(vs, scenario, k=2)
        if context:
            contexts.append(context)

    combined_context = "\n\n".join(contexts)

    prompt = f"""
Scenario:
{scenario}

Relevant information:
{combined_context}

Instructions:
- Provide a clear, practical, and concise recommendation.
- Use the provided information where relevant.
- If multiple approaches exist, consider them before deciding.
- Focus on actionable steps.
- Keep the answer under 200 words.
"""

    completion = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "system",
                "content": (
                    "You are a helpful, practical assistant that provides clear and grounded advice."
                ),
            },
            {"role": "user", "content": prompt},
        ],
        temperature=0.7,
        max_tokens=400,
    )

    return completion.choices[0].message.content


if __name__ == "__main__":
    # scenario = (
    #     "A student does not finish assigned work before deadline set by his supervisor. "
    #     "He notifies the supervisor late through email, 1 hour before the scheduled meeting. "
    #     "He doesn't get a reply. "
    #     "Meeting time passes and still no response from the supervisor.\n"
    #     "Problem: "
    #     "The student feels irresponsible and not sure about the suitable approach to the professor: "
    #     "shall he be apologetic or act as if nothing happened"
    # )

    # scenario = (
    #     "A software developer is working on a heavy project that consumes his mind all day. "
    #     "Even after work, his mind is trying to solve challenges faced through that day. "
    #     "This situation stays long enough for him to have a burnout. "
    #     "He tries to convey the message to the team leader, but faces a push to just keep working more. \n"
    #     "Problem: "
    #     "The software developer feels burnt out, unable to focus any more, and does not receive emotional support from his team leader. "
    #     "He is unsure about the best decision to save both his mental health and career."
    # )
    scenario = (
            "An accountant got laid off late in his career at the age of 55. "
            "Angry by the decision of the corporate where he spent nearly half his life, feels he shouldn't trust any employer anymore. "
            "He has a lot of family expenses to care for and needs an income. "
            "He's still not comfortable about working for someone again, so he starts thinking about starting his own business in accounting.\n"
            "Problem: "
            "The accountant understands the risk in starting a business and that it may take a long time to start generating an income large enough to cover his expenses. "
            "He's not able to weigh the risk against the possible benefits to take a decision."
        )

    print("=" * 70)
    print("SINGLE-AGENT RAG DECISION SYSTEM (NO ROLES)")
    print("=" * 70)
    print(f"\nScenario:\n{scenario}\n")
    print("=" * 70)

    print("\n[GENERATING FINAL RESPONSE...]\n")
    time.sleep(1)

    final_answer = single_agent_decision(scenario, vector_stores)

    print("=" * 70)
    print("FINAL RECOMMENDATION")
    print("=" * 70)
    print(f"\n{final_answer}\n")
    print("=" * 70)